base:
  applicationPort: 3000
  readinessPath: /status
  livenessPath: /status
  startupPath: /status
  image: 'sdshmctspublic.azurecr.io/c100/application:latest'
  ingressHost: c100-application.{{ .Values.global.environment }}.platform.hmcts.net
