# Note: in production we are forcing SSL and certificate verification.
# The RDS certificates bundle is downloaded in the Dockerfile.
#
# Refer to https://www.postgresql.org/docs/current/libpq-ssl.html for more information.
#
default: &default
  adapter: postgresql

development:
  <<: *default
  database: 'c100-development'
test:
  <<: *default
  database: 'c100-test'

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  sslmode: <%= ENV.fetch('DATABASE_SSLMODE', 'verify-full') %>
  sslrootcert: <%= ENV['RDS_COMBINED_CA_BUNDLE'] %>
